### ISSUE TITLE
RangeError on Layer.tiles in 0.4.0

### ISSUE THREAD

**Issue by juanitogan** [flame-engine/tiled.dart#13]
A RangeError is generated when accessing the Layer.tiles getter on non-square maps.  Latest 0.4.0 version.  This is due to the _tiles list being [x][y] and the tileMatrix and tileFlips lists being [y][x].  One or the other should be changed, or the addressing changed.  Someone else can decide which way to go with it.

When I tested correcting it, I got past the range errors but tiles in the map still didn't look right.  Its not my map (Flame's test map) so I didn't pursue it further at this time.

**Comment by erickzanardo** [comment]
@luanpotter can you take a look on this?
