### ISSUE TITLE
Spacing field in tmx file is not working

### ISSUE THREAD

**Issue by Jcupzz** [flame-engine/tiled.dart#29]
![tiles-5](https://user-images.githubusercontent.com/52130837/132131798-62a6db2c-dce3-493b-8296-0cde037c14b3.png)

 The above tiles image in Tiled Map Editor with `spacing = "1"` is working fine. But when it comes to flame_tiled its not working. 
The output I get is the below image with those yellow lines which are from the tile image above.

![flutter_01](https://user-images.githubusercontent.com/52130837/132132068-69b803fd-9472-405f-9098-111697643de1.png)

I am just a noob and I don't know if this occurs due to my code. Also, in the example file of flame_tiled repo the image doesn't have those yellow grid lines. 

The tmx file can be found in the repo attached below.
Please run this game for further reference
https://github.com/Jcupzz/Super-Mario.git

**Comment by luanpotter** [comment]
I think we dont have any example using that field, so it's very likely broken. I will test this against the new flame_tiled

**Comment by Jcupzz** [comment]
> I think we dont have any example using that field, so it's very likely broken. I will test this against the new flame_tiled

Ok cool!

**Comment by Hwan-seok** [comment]
Any news?

**Comment by spydon** [comment]
> Any news?

No news, if anyone want to take on this feel free! :)

**Comment by natebot13** [comment]
https://github.com/flame-engine/tiled.dart/blob/dece94deac65a4afd39ebe226b9bb6c4d6d7a604/lib/src/tileset/tileset.dart#L212-L213
This is the reason. Spacing shouldn't be added to the source rectangle. Removing the spacing fixes the issue.

**Comment by ufrshubham** [comment]
I see a PR is open for this but it is not approved. Is that not the correct fix for this issue?

**Comment by spydon** [comment]
> I see a PR is open for this but it is not approved. Is that not the correct fix for this issue?

I think it was just forgotten. Would be good if someone depended on the branch and tried the fix.

**Comment by ufrshubham** [comment]
@spydon I just tried to test that branch but the problem still persists. After debugging I found out that it was failing because spacing and margin parameters were not copied in `_checkIfExtenalTsx()` method.

**Comment by natebot13** [comment]
@ufrshubham interesting, I'm willing to take a look later today.

**Comment by natebot13** [comment]
This has been fixed with pull request #41 and I believe has been verified by @ufrshubham

**Comment by ufrshubham** [comment]
> This has been fixed with pull request #41 and I believe has been verified by @ufrshubham

Yes, I've tested that PR and it works.
