### ISSUE TITLE
ObjectGroup on tiles not getting parsed from .tsx file

### ISSUE THREAD

**Issue by lfraker** [flame-engine/tiled.dart#31]
I'm new to Flame and Tiled, so I may be doing something wrong, but I am trying to annotate collidable tiles in Tiles Collision Editor to simplify the work of creating repeated collidable game objects. When I import the TileMap via 

```dart
final TiledComponent tiledMap = await TiledComponent.load('tilemap.tmx', Vector2.all(50));
```
The objectGroup value is null on all Tiles, even though in the .tsx file there is an objectgroup node populated:

```xml
 <tile id="30" probability="0.5">
  <objectgroup draworder="index" id="6">
   <object id="11" x="3.25359" y="4.52951" width="25.3907" height="20.2233">
    <ellipse/>
   </object>
  </objectgroup>
 </tile>
```

I was looking through the repo, and it seems like the issue could simply be a camelCase instead of lowercase name in the Tile parser. in https://github.com/flame-engine/tiled.dart/blob/cb08bc937f82a6ed42cb47fa9b526446ea8e9f76/lib/src/tileset/tile.dart  on line 59, the parser tries to parse an 'objectGroup' node instead of an 'objectgroup' node:

```dart
objectGroup: parser.getSingleChildOrNullAs('objectGroup', Layer.parse)
```

Parsing objectGroups works correctly for tileMaps since the layer parsing code path uses the lowercase name (https://github.com/flame-engine/tiled.dart/blob/f719702b6be93edb46f972bceb1c431e40bf0f7d/lib/src/layer.dart on line 246):

```dart
xml.getChildrenAs('objectgroup', Layer.parse)
```

Please let me know if the above camelCase is intended, or if my use is not a supported case?
Is there another recommended way to simplify the defining of collision boxes on multiple terrain tiles?

**Comment by spydon** [comment]
It definitely looks like an error on our side (https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tmx-objectgroup). Do you want to put up a PR that fixes it? :)

**Comment by lfraker** [comment]
@spydon sure thing, will submit one shortly. I didn't see a contributing guide - any process I need to adhere to for the PR, or for something this simple can I just submit the change if all tests pass?

**Comment by spydon** [comment]
> @spydon sure thing, will submit one shortly. I didn't see a contributing guide - any process I need to adhere to for the PR, or for something this simple can I just submit the change if all tests pass?

The latter. :)

**Comment by lfraker** [comment]
@spydon I submitted a PR and included a new test case for this scenario: https://github.com/flame-engine/tiled.dart/pull/32

While testing, I noticed something interesting. It seems like whenever Tiles are being parsed from a TileSet, an extra tile is always added.

The parsed result is initialized as a new TileSet before returning, (https://github.com/flame-engine/tiled.dart/blob/main/lib/src/tileset/tileset.dart line 141).
In the TileSet initialization code, _generateTiles is called which iterates from 0 to numTiles, inclusive, and thus appends an extra Tile that was not included in the input file (https://github.com/flame-engine/tiled.dart/blob/main/lib/src/tileset/tileset.dart line 219):

```dart
for (var i = 0; i <= tileCount; ++i) {
      if (t.localId == i) {
        tiles.add(t);
        if (iterator.moveNext()) {
          t = iterator.current;
        }
      } else {
        tiles.add(Tile(localId: i));
      }
    }
```

I was curious what the reason was for the extra Tile. Should we simply ignore it?

**Comment by luanpotter** [comment]
A mistake, for sure! I imagine the extra tile never caused any issues, being empty.

**Comment by spydon** [comment]
Fixed by #32

**Comment by lfraker** [comment]
@spydon @luanpotter, forgot to update the package version in the PR. Are you able to bump the version so I can pull the latest package, or is there a release process for publishing?

Hoping to use this fix in a project I'm working on!

**Comment by spydon** [comment]
> @spydon @luanpotter, forgot to update the package version in the PR. Are you able to bump the version so I can pull the latest package, or is there a release process for publishing?
> 
> Hoping to use this fix in a project I'm working on!

I can do a release later today hopefully (you don't bump the version in the separate PRs, it's a separate process).

**Comment by spydon** [comment]
0.7.3 is now released!

**Comment by lfraker** [comment]
Awesome, thank you!
