### ISSUE TITLE
Issue when parsing multiple external tilesets.

### ISSUE THREAD

**Issue by lfraker** [flame-engine/tiled.dart#35]
Root causing this one was a bit of a wild chase through two repos, but it seems like when parsing a tiled map that references multiple external tilesets, all parsed tileset properties are all overwritten by the first external tileset file.

If I'm understanding the design correctly, if the Tileset is external and referenced in the .tmx file, via the 'source' property, then you need to pass in a TsxProvider to TileMapParser.parseTmx.

When parsing the tiled map in the flame engine, the code pulls the first tileset external reference, if available, and passes it in (https://github.com/flame-engine/flame/blob/5c47d7f6d7ed4705a3f19e9119364d9c6e6cff55/packages/flame_tiled/lib/src/renderable_tile_map.dart line 65):

```dart
TsxProvider? tsxProvider;
    if (tsxSourcePath != null) {
      tsxProvider = await FlameTsxProvider.parse(tsxSourcePath);
    } else {
      tsxProvider = null;
    }
    return TileMapParser.parseTmx(contents, tsx: tsxProvider);
```

This provider is passed through the parse tree for every tileset in the map (https://github.com/flame-engine/tiled.dart/blob/main/lib/src/tiled_map.dart line 221):

```dart
final tilesets = parser.getChildrenAs(
      'tileset',
      (e) => Tileset.parse(e, tsx: tsx),
    );
```

Subsequently, when each tileset is parsed, if a TsxProvider is given, it seems like every property that appears in the provided external reference overwrites the properties of the tileset being parsed (e.g. name, tilecount, etc.) See _checkIfExtenalTsx  method, https://github.com/flame-engine/tiled.dart/blob/main/lib/src/tileset/tileset.dart line 165.

I've been able to produce a repro of this issue with a local unit test. I've only tested multiple external tilesets, but it seems like an external + embedded tileset would potentially run into the same issue where the embedded tileset would be overwritten by the external tileset properties.

Since TsxProvider is simply a passthrough everywhere except the TileSet parser, would it be possible to generate the TsxProvider on the fly for each tileset here, rather than having the external caller pass it in?

(https://github.com/flame-engine/tiled.dart/blob/main/lib/src/tiled_map.dart line 221):

```dart
final tilesets = parser.getChildrenAs(
      'tileset',
      (e) => Tileset.parse(e, tsx: tsx),
    );
```
It seems like the way it was setup today was to support when a caller want's to pass in an external reference that isn't found in the .tmx file (not sure if this is a common use case)?

I plan to proceed with embedding all of the tilesets into my map file, so this is probably a lower-pri ask, but it would be nice to have this fix at some point if possible!

**Comment by spydon** [comment]
> It seems like the way it was setup today was to support when a caller want's to pass in an external reference that isn't found in the .tmx file (not sure if this is a common use case)?

That seems like a very uncommon usecase indeed.

> I plan to proceed with embedding all of the tilesets into my map file, so this is probably a lower-pri ask, but it would be nice to have this fix at some point if possible!

Do you want to be assigned to this issue?

Sorry for the slow response time on this issue, I had completely missed it. :)

**Comment by lfraker** [comment]
Sure, I can take this on if you're good with the proposal (pulling the generation of the TsxProvider into the parsing code)? The fix may take a bit too, can't get to this for a few days.

How do you want me to handle the TsxProvider named parameter passed into the parse method; mark as deprecated and update the code to ignore it, or remove it entirely? Either will require an update in the Flame repo (although I imagine the first would only fail analyzer runs).

Just joined the server, it's gdrwnd#6497

**Comment by spydon** [comment]
> Sure, I can take this on if you're good with the proposal (pulling the generation of the TsxProvider into the parsing code)?

Yeah, sounds like the logical thing to do.

> The fix may take a bit too, can't get to this for a few days.

No rush. :)

> How do you want me to handle the TsxProvider named parameter passed into the parse method; mark as deprecated and update the code to ignore it, or remove it entirely? Either will require an update in the Flame repo (although I imagine the first would only fail analyzer runs).

Can you mark just a parameter as deprecated? If that is possible then go for that.

**Comment by lfraker** [comment]
@spydon, finally got a chance to spend some time looking at a fix for this, and I think I have a better understanding of why TsxProvider is passed in. Implementations of TsxProvider have parse/getSource methods that have been written to enforce the consumer of the Tiled library's desired filepath prefix to the tilesets (e.g. FlameTsxProvider adds the prefix 'assets/tiles/' before each tileset 'source' property - see https://github.com/flame-engine/flame/blob/f777e1a0ea40bd589cb3eecd7c8f76b40d590f8b/packages/flame_tiled/lib/src/flame_tsx_provider.dart).

Unfortunately this means that a clean fix can't be implemented solely in this repo. When the map is parsed, the source property includes only the partial tileset path (everything after 'assets/tiles/').

This makes the fix a bit more involved. I think the cleanest options would be to either update the FlameTsxProvider getSource method to respect the key passed in and parse the tileset data on demand (it's currently stored), or to introduce another parallel static method  to TsxProvider/FlameTsxProvider that parses a tileset on demand, including the path prefix. The instance of FlameTsxProvider would then still be passed in to the parse method and used to generate the full path to each tileset.

I considered ways of making this fix in only the tiled repo, but everything I thought of would involve introducing Flame's special tileset path prefix to this repo, which is messy and breaks the clean separation between a parsing package and the engine enforcing the custom file structure.


This is not a blocking issue for me anymore (I just embedded all my tilesets), but I don't mind submitting PRs to both repos to fix this. Please let me know if you want me to proceed with the proposed fix (and if so, what the process is to ensure a coordinated release between packages)? Also, please let me know if you have any thoughts on a simpler fix that could be cleanly made in just the Tiled repo?

**Comment by spydon** [comment]
Alright, any of the fixes sounds good, choose the one you feel is the cleanest.

> Please let me know if you want me to proceed with the proposed fix (and if so, what the process is to ensure a coordinated release between packages)? 

Yes, please procees! :)
So we'll just have to release tiled.dart right before we release flame_tiled, you can depend on your tiled.dart branch meanwhile working on the PR and then when both PRs are done we'll release tiled.dart and swap over the flame_tiled dependency to that one.

> Also, please let me know if you have any thoughts on a simpler fix that could be cleanly made in just the Tiled repo?

I had a quick look but I couldn't come up with any.

**Comment by lfraker** [comment]
Sounds good, will try to get both PRs out over the next few days. Thanks!

**Comment by lfraker** [comment]
@spydon took a bit longer than expected, but finally got around to sending the two PRs. I mentioned this in the PRs, but decided to go with a slightly different fix than mentioned above, to avoid async propagation all the way through parsing code. I don't love the fix I went with either, so lmk if you have any suggestions for a better approach.

**Comment by spydon** [comment]
I just released `tiled.dart` 0.8.0 and `flame_tiled` 1.2.0 :slightly_smiling_face: 
I guess we can close this?

**Comment by lfraker** [comment]
Just undid the embedding of my tilesets and tested the fix - looks like it's working fine. Agree the issue can be closed, thanks!

**Comment by spydon** [comment]
> Just undid the embedding of my tilesets and tested the fix - looks like it's working fine. Agree the issue can be closed, thanks!

Super, good job!
