### ISSUE TITLE
Bump xml to latest (6.1.0)

### ISSUE THREAD

**Issue by netgfx** [flame-engine/tiled.dart#56]
# What could be improved
Bump xml to latest (6.1.0)

# Why should this be improved
Because we cannot upgrade packages that load both `tiled` and `xml`

# Any risks?

# More information

**Comment by spydon** [comment]
Do you want to put up a PR for this and make sure that everything runs as intended with the new `xml` package version?

**Comment by Hwan-seok** [comment]
I used xml with `6.1.0` since `6/2/2022` and worked fine with tiled.
Maybe I could PR for this
