### ISSUE TITLE
Object Layers expect ints, which prevents tmx file from loading

### ISSUE THREAD

**Issue by kickwaxapps** [flame-engine/tiled.dart#6]
The TmxObject.fromXML expects ints for x,y, width. height & rotation, but Tiled files have doubles. T

NodeDSL.on(element, (dsl) {
      name = dsl.strOr('name', name);
      type = dsl.strOr('type', type);
      **x = dsl.intOr('x', x);
      y = dsl.intOr('y', y);
      width = dsl.intOr('width', width);
      height = dsl.intOr('height', height);
      rotation = dsl.intOr('rotation', rotation);**
      gid = dsl.intOr('gid', gid);
      visible = dsl.boolOr('visible', visible);
    });`

**Comment by luanpotter** [comment]
can you please provide a sample of your tmx file? we are loading files without any problem with the current version. also please test against the latest version as there have been some major changes.

**Comment by luanpotter** [comment]
This is fixed by #16.
