### ISSUE TITLE
Ability to access the image rect for tiles

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/tiled.dart#63]
# Problem to solve

Each tile in a tileset has an `Image Rect` property which doesn't seem to be accessible in tiled.dart. Getting access to that property would allow users to use tiles from `Object` layers to spawn in sprite based components.

![image](https://user-images.githubusercontent.com/33748002/203013920-30f2f5f4-f797-4548-be4e-24b11f2d3b7c.png)

# Proposal

# More information

**Comment by spydon** [comment]
Should I assign you to this?

**Comment by ufrshubham** [comment]
> Should I assign you to this?

Sure, I can try to fix this.
